services:
  web:
    build: ./docker/php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - ./app/.env

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret123
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    env_file:
      - ./app/.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: app_user
      PMA_PASSWORD: secret123
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - ./app/.env

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
