name: Pipeline CD

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  deployment:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Déploiement sur le serveur de production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/domains/romyklk.me/public_html/symdeploy

            git pull origin production

            composer install --no-interaction --prefer-dist --optimize-autoloader

            php bin/console cache:clear --env=prod

            php bin/console doctrine:migrations:migrate --no-interaction

            php bin/console assets:install --symlink
